[package]
name = "fibonacci"
version = "0.1.0"
edition = "2021"

[dependencies]
jolt-sdk = { path = "../../../../jolt/jolt-sdk", features = ["host"] }
guest = { package = "fibonacci-guest", path = "./guest" }
hex = "0.4.3"
